# --- Example ---
[device]
log_sinks = uart, usb, sd:info
data_sinks = uart, usb, sd

[weather]
interval = 1m
sensors = temperature, humidity
rails = 5v
pulse_led = true

[rain]
external_int_pin = 7
sensors = tipping_bucket
rails = 5v

[heartbeat]
interval = 1h
host = http://localhost:4000/heartbeat
payload = full


# --- Reference ---
#
# [device]
# log_sinks    = sink[:level], ...  (levels: debug [default], info, warn, error)
# data_sinks   = sink, ...          (sinks: uart, usb, sd)
#
# [group]
# interval         = duration        (Go syntax: 5s, 3m, 1h)
# external_int_pin = pin
# sensors          = name, ...
# rails            = name, ...
# pulse_led        = true|false
# host             = url
# payload          = none|min|full
#
#
# --- Feather M0 + Hypnos defaults ---
#
# [device]
# log_sinks    = uart:debug, usb:debug
# data_sinks   = uart, usb
