# --- Example ---
[device]
log_sinks = sd:info
data_sinks = sd

[weather]
interval = 1m
sensors = temperature, humidity
pulse_led = true

[rain]
external_int_pin = 7
sensors = tipping_bucket

[heartbeat]
interval = 1h
host = http://localhost:4000/heartbeat
payload = full


# --- Reference ---
#
# [device]
# data_sinks   = sink, ...          (sinks: serial, sd)
# log_sinks    = sink[:level], ...  (levels: debug [default], info, warn, error)
#
# [group]
# interval         = duration        (Go syntax: 5s, 3m, 1h)
# external_int_pin = pin
# sensors          = sensor_id, ...
# pulse_led        = false [default] | true
# host             = url
# payload          = none [default] | min | full
